package com.moscool.agent.model

/**
 * Supported AI provider types.
 */
enum class AIProviderType(val displayName: String) {
    OPENAI("OpenAI"),
    GEMINI("Google Gemini"),
    OPENROUTER("OpenRouter"),
    GROQ("Groq"),
    CUSTOM_OPENAI("OpenAI-Compatible (Custom)")
}

/**
 * Configuration for an AI provider.
 */
data class AIProviderConfig(
    val providerType: AIProviderType = AIProviderType.CUSTOM_OPENAI,
    val apiKey: String = "",
    val baseUrl: String = "",
    val model: String = "",
    val maxTokens: Int = 4096,
    val temperature: Double = 0.7
) {
    val isValid: Boolean
        get() = apiKey.isNotBlank() && model.isNotBlank()

    fun defaultBaseUrl(): String = when (providerType) {
        AIProviderType.OPENAI -> "https://api.openai.com/v1"
        AIProviderType.GEMINI -> "https://generativelanguage.googleapis.com/v1beta"
        AIProviderType.OPENROUTER -> "https://openrouter.ai/api/v1"
        AIProviderType.GROQ -> "https://api.groq.com/openai/v1"
        AIProviderType.CUSTOM_OPENAI -> ""
    }

    fun effectiveBaseUrl(): String = baseUrl.ifBlank { defaultBaseUrl() }
}

/**
 * A chat message for the AI API.
 */
data class ChatMessage(
    val role: String,
    val content: String,
    val name: String? = null
)

/**
 * The response from an AI provider.
 */
data class AIResponse(
    val content: String,
    val toolCalls: List<ToolCall> = emptyList(),
    val finishReason: String? = null,
    val usage: TokenUsage? = null
)

data class ToolCall(
    val id: String,
    val name: String,
    val arguments: Map<String, Any?>
)

data class TokenUsage(
    val promptTokens: Int = 0,
    val completionTokens: Int = 0,
    val totalTokens: Int = 0
)

/**
 * Social media post content generated by the AI.
 */
data class SocialPost(
    val hook: String = "",
    val body: String = "",
    val callToAction: String = "",
    val hashtags: List<String> = emptyList(),
    val fullText: String = ""
) {
    companion object {
        fun fromFullText(text: String): SocialPost {
            return SocialPost(fullText = text)
        }
    }
}

/**
 * Template types for social media content generation.
 */
enum class ContentTemplate(val displayName: String) {
    EDUCATIONAL("Educational"),
    PROMOTIONAL("Promotional"),
    STORYTELLING("Storytelling"),
    QUESTION("Question"),
    POLL_STYLE("Poll-style"),
    TIPS("Tips"),
    MYTH_VS_FACT("Myth vs Fact"),
    PROBLEM_SOLUTION("Customer Problem/Solution"),
    BEHIND_THE_SCENES("Behind the Scenes")
}
